### ISSUE TITLE
implicite creation of data structures

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/python-jsonpreprocessor#74]
database_works.jsonp, creates parameter structures explicitly, i.e. 3 lines are required to create a 3-level parameter structure, this works as expected
{
            "${params.global.dDATABASE}": {},
            "${params.global.dDATABASE.BITS}" : {},
            "${params.global.dDATABASE.BITS.bSupported}" : true
}

database_works_not.jsonp, tries the same but implicitly, i.e. one liner is only required to create the same 3-level structure as above, but this is not working as expected

{
            "${params.global.dDATABASE.BITS.bSupported}" : true
}

In this case following error is raised:
[ ERROR ] Loading of JSON configuration file failed! 
          Reason: Could not set variable 'params['global']['dDATABASE']['BITS']['bSupported']' with value 'True'!

Expectation can be found in original feature request https://rb-tracker.bosch.com/tracker01/browse/ROBFW-372, esp. in picture attached to that issue

**Comment by namsonx** [comment]
Hello Thomas,

When set only one line "${params.global.dDATABASE.BITS.bSupported}" : true the error occurred due to "dDATABASE.BITS" element is not available. At the beginning, we designed ${} syntax to overwrite or add new element to the exist parameters.

In case we want to make the enhancement for this requirement, there is a constraint we need to clarify:
     - **dotdict format:** for example, user adding one line  ${params.global.dDATA.BASE.BITS.bSupported} : true where "dDATA.BASE" user considers as 1 element. This case, dotdict format of jsonpreprocessor could not be aware.

Thank you,
Son

**Comment by HolQue** [comment]
How about this:
* `${params.global.dDATABASE.BI.TS.bSupported}`
* `${params}['global']['dDATABASE']['BI.TS']['bSupported']`

Will this cause the same result?

Regarding: `['BI.TS']`

Is this a key with name `'BI.TS'`, or will this be a key `'BI'` with subkey `'TS'`?

**Comment by HolQue** [comment]
We usually initialize new dictionaries in this way:

`dDATABASE = {}`

(and not `${params.global.dDATABASE}`)

The scope `params.global` is only required when referring to an already existing parameter.

Therefore I would expect this:

`${dDATABASE.BITS.bSupported} : True`

(and not `${params.global.dDATABASE.BITS.bSupported : True}`)

**Comment by HolQue** [comment]
And I would also expect that it is not allowed to have dots at top level (name of the dictionary):

`${dDATA.BASE} : True`

**Comment by namsonx** [comment]
Hello Holger,

The cases you mentioned:

- ${params.global.dDATABASE.BI.TS.bSupported}

- ${params}['global']['dDATABASE']['BI.TS']['bSupported']

Both cases are allowed with the condition that "BI.TS" was exist, it works fine with dotdict or traditional formats.

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

my question was not if it's allowed. I asked about the result.

And regarding "_with the condition that "BI.TS" was exist_". This criteria is not relevant in this context, because this issue is about the implicite creation of data structures. This means, all key levels do not exist at the beginning.

I only want to be sure to understand the feature correctly.

Example:

Is my understanding correct, that

`${AA.BB.CC.DD} : 25`

is resolved to

`"AA" : {"BB" : {"CC" : {"DD" : 25}}}`

and

`${AA}['BB.CC']['DD'] : 25`

is resolved to

`"AA" : {"BB.CC" : {"DD" : 25}}`

?

**Comment by HolQue** [comment]
Other question:

What shall happen in case of a mixture of explicite and implicite creation?

```
"AA" : {},
${AA}["BB"] : {},
${AA.BB.CC.DD} : 25
```

Will this be resolved correctly to:

`"AA" : {"BB" : {"CC" : {"DD" : 25}}}`

?

**Comment by test-fullautomation** [comment]
Hi Holger,
this should work.
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas,

This ticket was implemented in the [commit bae1028e](https://github.com/test-fullautomation/python-jsonpreprocessor/commit/bae1028e08531619593105592fd21b6c7f8773f3) on stabi branch ([namsonx/task/stabi_branch](https://github.com/test-fullautomation/python-jsonpreprocessor/tree/namsonx/task/stabi_branch))

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful

**Comment by test-fullautomation** [comment]
solved and already merged #147
